/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.JOptionPane;
import model.bean.ClimbingStatistics;
import model.dao.ProdutoDAO;

/**
 *
 * @author Marcello
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connectionDataset = new javax.swing.JButton();
        VisualizarDataset = new javax.swing.JButton();
        nameDataset = new javax.swing.JLabel();
        nameAutor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        connectionDataset.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        connectionDataset.setText("Canectar Dataset no Banco de Dados");
        connectionDataset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectionDatasetActionPerformed(evt);
            }
        });

        VisualizarDataset.setText("Visualizar Dataset");
        VisualizarDataset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarDatasetActionPerformed(evt);
            }
        });

        nameDataset.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        nameDataset.setText("DATASET: Climbing Statistics");

        nameAutor.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        nameAutor.setText(" Marcello Diniz");
        nameAutor.setPreferredSize(new java.awt.Dimension(98, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 179, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(VisualizarDataset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(nameDataset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(connectionDataset)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(nameDataset)
                .addGap(37, 37, 37)
                .addComponent(connectionDataset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(VisualizarDataset)
                .addGap(80, 80, 80)
                .addComponent(nameAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void connectionDatasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionDatasetActionPerformed
        ClimbingStatistics p = new ClimbingStatistics();
        ProdutoDAO dao = new ProdutoDAO();

        try {
            int i = 0, j = 0, opcao;
            Reader reader = Files.newBufferedReader(Paths.get("C:\\Users\\marce\\Downloads\\mount-rainier-weather-and-climbing-data\\climbing_statistics.csv"));
            CSVReader csvReader = new CSVReaderBuilder(reader).withSkipLines(1).build();

            List<String[]> colunas = csvReader.readAll();
            for (String[] coluna : colunas) {
                p.setDate1(coluna[0]);
                p.setRoute(coluna[1]);
                p.setAttempted(coluna[2]);
                p.setSucceeded(coluna[3]);
                p.setSuccessPercentage(coluna[4]);

                dao.create(p);

                i++;
                j++;

                if (j == 1000) {
                    opcao = JOptionPane.showConfirmDialog(null, "Você já carregou " + i + " dados no Banco. Deseja Continuar?", "Escolha", JOptionPane.YES_NO_OPTION);
                    j = 0;

                    if (opcao == 0) {
                        continue;
                    } else {
                        i = 0;
                        break;
                    }
                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_connectionDatasetActionPerformed

    private void VisualizarDatasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarDatasetActionPerformed
        new TelaTabela().setVisible(true);
        dispose();
    }//GEN-LAST:event_VisualizarDatasetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VisualizarDataset;
    private javax.swing.JButton connectionDataset;
    private javax.swing.JLabel nameAutor;
    private javax.swing.JLabel nameDataset;
    // End of variables declaration//GEN-END:variables

    private void lerTabela() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
